name: Auto-Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'


permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build
      run: |
        bash $GITHUB_WORKSPACE/build-actions.sh
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto-Build"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
